name: navis_push_worker
description: A Very Good Project created by Very Good CLI.
version: 2.2.22
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  collection: ^1.18.0
  crypto: ^3.0.7
  dart_firebase_admin: ^0.4.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.3.0
  hive: ^2.2.3
  http: ^1.6.0
  intl: ^0.20.2
  logger: ^2.6.2
  shorebird_redis_client: ^0.0.10
  time: ^2.1.4
  worldstate_models:
    git:
      url: https://github.com/SlayerOrnstein/wfcd_dart.git
      path: packages/worldstate_models
      ref: worldstate_models-v0.1.1+7

dev_dependencies:
  husky: ^0.1.7
  mocktail: ^1.0.0
  test: ^1.26.3
  very_good_analysis: ^10.0.0
