name: navis_push_worker
description: A Very Good Project created by Very Good CLI.
version: 2.2.17
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  collection: ^1.18.0
  crypto: ^3.0.7
  dart_firebase_admin: ^0.4.0
  googleapis: ^15.0.0
  googleapis_auth: ^1.6.0
  hive: ^2.2.3
  http: ^1.5.0
  intl: ^0.19.0
  mason_logger: ^0.3.3
  shorebird_redis_client: ^0.0.10
  time: ^2.1.4
  warframe_drop_data:
    git:
      url: https://github.com/SlayerOrnstein/wfcd_dart.git
      path: packages/warframe_drop_data
      ref: acbac173e92d4d999921d4b3ab8fa01ee578cc4c
  worldstate_models:
    git:
      url: https://github.com/SlayerOrnstein/wfcd_dart.git
      path: packages/worldstate_models
      ref: acbac173e92d4d999921d4b3ab8fa01ee578cc4c

dev_dependencies:
  husky: ^0.1.7
  mocktail: ^1.0.0
  test: ^1.26.3
  very_good_analysis: ^10.0.0
